### ISSUE TITLE
Question about data source compatibility

### ISSUE THREAD

**Issue by memyselfandm** [uber/grafana-dash-gen#66]
I have influxDB as my TSDB. I see that the `Target()` uses Graphite line syntax. Can I use this library with my InfluxDB-based Grafana instance?

**Comment by albertyw** [comment]
You can put whatever string you want into Target and it'll be copied into the grafana dashboard as is.

**Comment by memyselfandm** [comment]
I did some more digging and testing and, unfortunately, it's not that simple. The structure of the `target` objects appears to be very different from datasource to datasource. In addition to that, the library does some extra processing on `targets` when the dashboard is generated that doesn't allow one to bypass the `Target` class and just write custom objects into `targets:`. 

I think the course of action here would be to make the `Target` class more generic and have datasource-specific subclasses of it, but admittedly I don't think my JS is good enough to pull that off without mucking things up.

As an example, here is a target object from a graph panel with an InfluxDB datasource:
````javascript
{
              "groupBy": [
                {
                  "params": [
                    "$__interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "action_type"
                  ],
                  "type": "tag"
                },
                {
                  "params": [
                    "none"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "my_data_counter",
              "orderByTime": "ASC",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "last"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=",
                  "value": "ABC123"
                }
              ]
            }
```
