### ISSUE TITLE
No Valid JSON generated

### ISSUE THREAD

**Issue by Sarabor** [uber/grafana-dash-gen#68]
Hello,

I am currently trying to get the example.js to work. I have the same problem as in this issue https://github.com/uber/grafana-dash-gen/issues/49 and sadly the answers did not help me.

So then I tried to just get the dashboard JSON Code instead of publishing the dashboard into Grafana.
I changed 

>   grafana.publish(dashboard);

to

>  console.log(dashboard.generate()); 

so I get a log of the JSON Code. This works just fine. So then I tried to manually import the JSON Code from a file into Grafana via Grafana's Import option. However I got the following error message from Grafana and the dashboard was not created. 

> JSON -> JS Serialization failed: Unexpected token i in JSON at position 5 

I then put the JSON Code into https://jsonformatter.curiousconcept.com/# to see if the generated JSON Code was valid.
The formatter inserted missing quotes and replaces incorrect quotes as seen in the picture.

![Jsonformatter](https://user-images.githubusercontent.com/73877403/110259954-8061e800-7faa-11eb-9fa1-5516f9e24a58.PNG)

I tried to import the new JSON Code and this time the import was successful and a dashboard was created. However instead of panels the dashboard shows only one error message.

![Dashboarderror](https://user-images.githubusercontent.com/73877403/110260006-c28b2980-7faa-11eb-82e5-5f80abe4e228.PNG)

Is there something I am doing wrong or is the generated JSON Code not valid?

If you need anymore information please let me know.

Here is the JSON Code I used:

Generated JSON Code from example.js:

>  {
>   id: null,
>   title: 'TEST API dashboard',
>   originalTitle: 'Generated Dashboard',
>   tags: [ 'myapp', 'platform' ],
>   style: 'dark',
>   timezone: 'browser',
>   editable: true,
>   hideControls: false,
>   sharedCrosshair: false,
>   refresh: '1m',
>   schemaVersion: 6,
>   hideAllLegends: false,
>   time: null,
>   rows: [
>     {
>       title: 'Request Volume',
>       height: '250px',
>       editable: true,
>       collapse: false,
>       panels: [Array],
>       showTitle: true
>     },
>     {
>       title: 'System / OS',
>       height: '250px',
>       editable: true,
>       collapse: false,
>       panels: [Array],
>       showTitle: true
>     }
>   ],
>   templating: { list: [ [Object], [Object] ], enable: true },
>   annotations: { list: [ [Object] ], enable: true }
> }

Code after JSON Formatter:

> {
>    "id":null,
>    "title":"TEST API dashboard",
>    "originalTitle":"Generated Dashboard",
>    "tags":[
>       "myapp",
>       "platform"
>    ],
>    "style":"dark",
>    "timezone":"browser",
>    "editable":true,
>    "hideControls":false,
>    "sharedCrosshair":false,
>    "refresh":"1m",
>    "schemaVersion":6,
>    "hideAllLegends":false,
>    "time":null,
>    "rows":[
>       {
>          "title":"Request Volume",
>          "height":"250px",
>          "editable":true,
>          "collapse":false,
>          "panels":[
>             "Array"
>          ],
>          "showTitle":true
>       },
>       {
>          "title":"System / OS",
>          "height":"250px",
>          "editable":true,
>          "collapse":false,
>          "panels":[
>             "Array"
>          ],
>          "showTitle":true
>       }
>    ],
>    "templating":{
>       "list":[
>          [
>             "Object"
>          ],
>          [
>             "Object"
>          ]
>       ],
>       "enable":true
>    },
>    "annotations":{
>       "list":[
>          [
>             "Object"
>          ]
>       ],
>       "enable":true
>    }
> }
 
Edit: Fixed links

**Comment by albertyw** [comment]
It seems that the readme update should have resolved this issue
